# Generated by Django 5.0.6 on 2024-06-18 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsdBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserChat', models.TextField()),
                ('BotChat', models.TextField()),
                ('chat_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Autism_Bot', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
