# Generated by Django 5.0.6 on 2024-06-18 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asd', '0002_asdbot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AsdBot',
            new_name='AsdBotModel',
        ),
        migrations.RenameField(
            model_name='asdbotmodel',
            old_name='BotChat',
            new_name='AIMessage',
        ),
        migrations.RenameField(
            model_name='asdbotmodel',
            old_name='UserChat',
            new_name='HumanMessage',
        ),
    ]
